project:
  type: website

website:
  title: "John Sterrett"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Sterrett_resume.pdf
        text: Resume
      - href: Sterrett_CV.pdf
        text: Academic CV
      - text: Educational Resources
        menu:
        - text: Using Snakemake on Clusters
          url: https://sterrettjd.github.io/Effective-Snakemake-HPC
        - text: Jornet microbiome analysis
          url: Edu/Kilian_microbiome.html
      - text: Race Reports
        menu:
        - text: Trail of Fears '23
          url: race_reports/trail_of_fears_23.html
        - text: Vol State 500k '24 (DNF)
          url: race_reports/vol_state_500k_24_dnf.html
    tools:
      - icon: github
        menu:
          - text: My GitHub
            url:  https://github.com/sterrettJD/
          - text: Site Repo
            url:  https://github.com/sterrettJD/sterrettJD.github.io

format:
  html:
    theme: sandstone 
    css: styles.css
    toc: true
