project:
  type: website

website:
  title: "John Sterrett"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Sterrett_CV_23_10.pdf
        text: CV
    tools:
      - icon: github
        menu:
          - text: My GitHub
            url:  https://github.com/sterrettJD/
          - text: Site Repo
            url:  https://github.com/sterrettJD/sterrettJD.github.io

format:
  html:
    theme: sandstone 
    css: styles.css
    toc: true
