project:
  type: website

website:
  title: "John Sterrett"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Sterrett_CV_23_10.pdf
        text: CV


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
