---
title: "Vol State 500k 2024 (DNF) race report"
---

**NOTE:** This is a live document. It is unfinished and largely unedited and will change. Don't quote me.

> “Some of you may experience mild to severe sleep deprivation during this race. Make sure to keep things safe” – Carl (race director), at the Last Supper, aka the pre-race meeting (statement is approximate)

# Starting my race 

10 years ago, I ran my first half marathon when I was 14. I remember coming home and (in an act of naïve curiosity) googling  “how far can people run” and “what are the longest races”. That day, I found out about a 314-mile footrace that passed just 2 miles from my house every summer. While I continued to live near the course, I’d go out and pass out water and Gatorade as the race went by (I didn't do this reliably, but it happened nonetheless).

This year, I decided it was my turn to make the trek. I’ve had a tumultuous ~8 year ultrarunning “career” since high school, though 4 of those years were spent injured and unable to run more than 20 miles per week. The past 4 years have been relatively smooth, with a couple of races and a larger number of self-supported ultra-distance days up in the mountains and around Boulder.

Mostly, over the past few years I’ve been very drawn to trail/mountain ultras. I’ve been drawn into runs like Cruel Jewel (59 mi/15,000ft of elevation gain), 4 laps of Boulder Skyline Traverse (69 mi/27,000ft gain), and classic backcountry runs like Pawnee-Buchanan and a double crossing of the Grand Canyon (R2R2R).

With these, I’ve done a few ~24 hr efforts and got ambitious about pushing into multi-day ultras. That 314-mile race that I learned about 10 years ago has been in the back of my mind for quite a while now, so with the encouragement of a few friends, I threw my name in the ring for this year’s Vol State 500k.

Vol State is a 314 mile footrace on roads across Tennessee, from Missouri to Georgia, during the peak of the summer. The heat index is typically around 100F (37C) each day, and it's so humid that nothing ever dries. People who have been around the 24+hr road ultra racing scene for any amount of time probably know it as one of Lazarus Lake’s infamous races, a journey run full of suffering. 

I find myself not opposed to suffering, and I think I have a decent tolerance for it. But I really didn’t know what I was getting myself into. I’ve heard many times that “Vol State is a different breed of race”, but as someone with a prefrontal cortex that still probably isn’t fully developed, I had to learn the hard way. 

# Ending my race
I’ll have a description of how my race went below, but here’s how it ended/a reflection.


## Disrupted expectations
I pulled the plug at mile 104. For some reason, I expected that I'd enjoy the sleep deprivation, but that was really not the case. After the first sleep deprived night, stumbling across the shoulder of the highway, trying not to step in front of any semi trucks, I decided I really had no interest in doing that for at least 3 additional nights. I thought that the nights would be meditative, but I mostly found them troublesome, as I was slapping myself and singing trying to stay awake.

I realized that this would be more of a sleep deprivation competition than a pure athletic endeavor, as you're mostly forced to sleep during the day and run at night due to the heat. It's also not a trail or mountain run. While that wasn't a surprise, I thought that i'd still be able to appreciate the course, since it goes straight through the area that I grew up in. 

I expected to feel connected to the course as I traversed my home for the first 17 years of my life. I had drilled into my head these romantic ideas of some spiritual connection to crossing my home state. In reality, I didn't feel very connected to the course, or the kind of running I was doing, or the idea of more sleep deprived nights. At this point, I started looking for what else I could be getting out of the race, and the only thing I could come up with was growth through discomfort and suffering.

## On suffering and what I want from running
By now, I can suffer for a while, and I've suffered for a while many times. I'm not sure I'm growing much by putting myself into a controlled descent of the waterfall of discomfort. A few years ago, I would have gladly entered that descent with the goal of growing through it, but now I know there's a lot of growth possible outside of situations that require extreme physical discomfort. I think there's a lot of growth to come these days for me through spending a little more time slowed down, connecting with and showing up for the people in my life.

Maybe I would've been a better person through sticking to what I signed up for? Probably. Would I be a better person from doing that at the sacrifice of other adventures that feel more connecting and spritually fulfilling? I'm not so sure.

For many years, I've considered my ability to show up continuously through things to be one of my strengths as a runner and probably as a person. Sometimes that takes form in running by granny-gearing for hours through a low until I start feeling better, or it's taken the form of doing 500 hours physical therapy over the course of two years while working through IT band issues. Stubbornness and grit like that are really celebrated in the ultrarunning community, and I built part of my identity around it, given that I started in the sport at such a young age. That grit's definitely burned me in the past, and it's burned me out of things I really loved. The ability to grind through something is a great skill to have, but it needs to be equally balanced by an ability to know when to do that and an ability to know when you should show up with malleability instead. A lot of strength comes from knowing when to not be firm all of the time.

In reality, I kind of think that my relationship with running is at a point where I don't need to seek out suffering for the sake of suffering. Maybe I just like to do fun things, and while I thought Vol State would be fun, it turned out that "fun" wasn't the opportune word.


## How much should a race align with your values?
If I kept going, it would be at the expense of big days with friends in the Colorado high country this summer, my early fall 100 miler plans (Mountain Lakes???), and trying to get my first Western States and Hardrock qualifiers. 

I think about running "shorter" races, like 50 miles, where it feels okay to trash your body without knowing why you're doing it, since the recovery isn't unreasonably long. But for Vol State, you spend the first few days digging your grave and then next few getting buried alive in it - and that's not something that should be done in a cavalier manner without regards to your personal values. 

That just didn't feel worth it for a race that wasn't fun. So I pulled.

I hadn't listened to the [SWAP](https://swaprunning.com/) podcast in a while, but I did for the first time on my drive home and David said something that really resonated, along the lines of "We shouldn't be judged on chasing the limits of human performance but instead based on how we pursue what fulfills us in our brains."

I thought I would be really excited to test the limits of performance for myself - but you really can't test those limits too often, and there seems to be a component where you just have to be willing to dig that grave. Some part of me thinks that has to line up with what you value as a person. I thought that I valued revisiting my old home in enough to make this worth it - and I also wanted to prove myself in this place. But I learned that I didn't need to prove myself to the community, to Laz, or even myself. 

## Death of an ego
Part of your ego dies a little when you DNF, especially when a lot of your identity is rooted in a sport that hyperfocuses on grit. Today, that death feels like a healthy process of pruning a plant. I had ideas around running fast and learning how deep I could dig, and honestly some hope of impressing Laz so that maybe I can run Barkley one day. But I had to come to terms with the fact that the perseverance is something that hasn't always served me in life and won't always continue to benefit me. The ability to suffer isn't that much of a virtue.

I think I can prune a little perseverance and probably grow more effectively in the long run. 

Maybe not - maybe I'm just a baby. I don't really care too much. Maybe the fact that I wrote this many words means that I do care a lot. There's a lot of maybe.


# The race
To be continued...